CREATE DATABASE Pregatire

GO
USE Pregatire

CREATE TABLE R
( A INT,
  B INT,
  C INT
);

CREATE TABLE S
( A INT,
  D INT
);

INSERT INTO R(A,B,C) VALUES(1,2,3),(1,2,4),(3,3,5);
INSERT INTO S(A,D) VALUES(1,4),(1,7),(3,8);

SELECT * FROM R;
SELECT * FROM S;

--SELECT DISTINCT R.B FROM R LEFT OUTER JOIN S ON R.B=S.A
SELECT DISTINCT S.A FROM R RIGHT OUTER JOIN S ON R.C=S.D

